catalogMode: prefer
cleanupUnusedCatalogs: true
shellEmulator: true
trustPolicy: no-downgrade
trustPolicyExclude:
  - chokidar@4.0.3

packages:
  - packages/*
  - playground
  - examples/*

catalog:
  '@antfu/eslint-config': ^7.4.3
  '@antfu/utils': ^9.3.0
  '@types/node': ^25.2.3
  '@typescript/native-preview': 7.0.0-dev.20251204.1
  bumpp: ^10.4.1
  eslint: ^10.0.0
  lodash-es: ^4.17.23
  tsdown: ^0.20.3
  typescript: ^5.9.3
  unplugin-quansync: ^0.5.1
  unplugin-unused: ^0.5.7
  vite: ^7.3.1
  vitest: ^4.0.18

catalogs:
  prod:
    '@quansync/fs': ^1.0.0
    defu: ^6.1.4
    jiti: ^2.6.1
    quansync: ^1.0.0
onlyBuiltDependencies:
  - esbuild
